exports.environments = {
  'continuous-integration': {
    url: 'http://buy-ci-cloud-01.bellevue.agilysys.com:8080', //need to be updated
    basePath: '/kiosk-desktop-service/application/ui',
    tenant: 'tenantforig4410',
    username: 'buy_test',
    password: 'Pa$$word5',
    tenantId: '32',
    businessContextId: 'ea2e44ee-46d9-4c90-8f7a-58ed389493d6',
    ondemandConfigId: '5d24c882799ab5001363cf47',
    domain: 'http://buy-ci-cloud-01.bellevue.agilysys.com:8080/',
    firstName: 'admin',
    lastName: 'admin',
    multipleContexts: false,
    email: 'buy_admin_00@agilysys.com',
    usernameWithSecurityQuestion: 'buy_test1',
    usernameWithoutSecurityQuestion: 'no_answer',
    usernameWithLockedAccount: 'locked_user',
    usernameToTestLockScenario: 'lock_test_user',
	  displayProfile: '109738',
	  storeBusinessContext: 'c9d024f3-67ac-49eb-9dd2-b962c9f62ef6',
	  backOfficeURL: 'http://buy-ci-cloud-01.bellevue.agilysys.com:8080'
  },
    local: {
    url: 'http://localhost:8080/application/ui'
    },
  test: {
    url: 'http://buy-test-buy-01.bellevue.agilysys.com:8080',
    basePath: '/kiosk-desktop-service/application/ui/login',
    tenant: 'test01',
    username: 'buy_admin',
    firstName: 'admin',
    email: 'buy_admin_33@agilysys.com'
  },
  integration: {
    url: 'https://buy-int.hospitalityrevolution.com',
    basePath: '/kiosk-desktop-service/application/ui',
    tenant: 'igsystem4intbackcompat',
    username: 'buy_test',
    password: 'Pa$$word5',
    tenantId: '198',
    businessContextId: 'd9516c94-3d7b-45bf-af4b-aabe09f1eeef',
    ondemandConfigId: '5c703a3381f9610009182630',
    domain: 'http://buy-int.hospitalityrevolution.com',
    firstName: 'admin',
    lastName: 'admin',
    multipleContexts: true,
    email: 'buy_admin_00@agilysys.com',
    usernameWithSecurityQuestion: 'buy_test1',
    usernameWithoutSecurityQuestion: 'no_answer',
    usernameWithLockedAccount: 'locked_user',
    usernameToTestLockScenario: 'lock_test_user',
      displayProfile: '30612',
      storeBusinessContext: '598be85d-82d4-4585-8b17-9a90ead91b37',
	  backOfficeURL: 'https://buy-int.hospitalityrevolution.com:443'
  },
  integration_manualStore: {
    url: 'https://buy-int.hospitalityrevolution.com',
        basePath: '/kiosk-desktop-service/application/ui',
        tenant: 'igsystem4intbackcompat',
        username: 'buy_test',
        password: 'Pa$$word5',
        tenantId: '198',
        businessContextId: 'd9516c94-3d7b-45bf-af4b-aabe09f1eeef',
        ondemandConfigId: '5c703a3381f9610009182630',
        domain: 'http://buy-int.hospitalityrevolution.com',
        firstName: 'admin',
        lastName: 'admin',
        multipleContexts: true,
        email: 'buy_admin_00@agilysys.com',
        usernameWithSecurityQuestion: 'buy_test1',
        usernameWithoutSecurityQuestion: 'no_answer',
        usernameWithLockedAccount: 'locked_user',
        usernameToTestLockScenario: 'lock_test_user',
          displayProfile: '39720',
          storeBusinessContext: 'b649362f-6e35-444f-9c8b-ef341421d39a',
    	  backOfficeURL: 'https://buy-int.hospitalityrevolution.com:443'
  },
  integration_automationStore: {
        url: 'https://buy-int-auto.hospitalityrevolution.com',
        basePath: '/kiosk-desktop-service/application/ui',
        tenant: 'igsystem4intbackcompat',
        username: 'buy_test',
        password: 'Pa$$word5',
        tenantId: '1204',
        businessContextId: '    ',
        ondemandConfigId: '5ed6076b3b00f6001495f414',
        domain: 'http://buy-int-auto.hospitalityrevolution.com',
        firstName: 'admin',
        lastName: 'admin',
        multipleContexts: true,
        email: 'buy_admin_00@agilysys.com',
        usernameWithSecurityQuestion: 'buy_test1',
        usernameWithoutSecurityQuestion: 'no_answer',
        usernameWithLockedAccount: 'locked_user',
        usernameToTestLockScenario: 'lock_test_user',
        displayProfile: '64201',
        storeBusinessContext: '48fee567-1e9f-416b-88c1-9c6b71d3df92',
        backOfficeURL: 'https://buy-int.hospitalityrevolution.com:443'
  },

  post: {
    url: 'https://buy-post.hospitalityrevolution.com/',
    tenant: 'test01',
    username: 'buy_admin',
    password: 'Pa$$word5'
  }
};
