pool:
  name: Hosted VS2017
steps:
- task: NodeTool@0
  displayName: 'Use Node version'
  inputs:
    versionSpec: 10.14

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: 'Use Yarn 1.x'
  inputs:
    checkLatest: true

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: 'Yarn '
  inputs:
    projectDirectory: '$(system.defaultworkingdirectory)'
    arguments: 'install  --force'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: 'Yarn '
  inputs:
    projectDirectory: '$(system.defaultworkingdirectory)'
    arguments: build

- task: ArchiveFiles@2
  displayName: 'Archive application'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
