// Copyright © 2018-2019 Agilysys NV, LLC.  All Rights Reserved.  Confidential Information of Agilysys NV, LLC.

import path from 'path';
import FileWriter from './file-writer';

var HOST = '0.0.0.0';
var PORT = '8080';

var env = [
    '###',
    '### WARNING: This file is generated by ' + path.basename(__filename) + ' - do not edit manually!',
    '### ' + process.env.NODE_ENV,
    '',
    'NODE_ENV=' + (process.env.NODE_ENV === 'development' ? 'development' : 'production'),
    'HOST=' + HOST,
    'PORT=' + PORT
];
if (process.env.NODE_ENV === 'development') {
  env.push('RMQ_SERVICE=amqp:buy-dev-rmq-01.bellevue.agilysys.com:5672');
  env.push('DOMAIN=' + process.env.DOMAIN);
  env.push('WORKSTATION=true');
}

module.exports = function () {
    FileWriter.write('.env', env.join('\n'));
};
