// Copyright © 2018-2019 Agilysys NV, LLC.  All Rights Reserved.  Confidential Information of Agilysys NV, LLC.

import path from 'path';
import FileWriter from 'node_scripts/tools/file-writer';
import config from 'app.config';

var eslintIgnore = [
  '###',
  '### WARNING: This file is generated by ' + path.basename(__filename) + ' - do not edit manually!!',
  '###',
  '',
  path.relative(config.paths.root, config.paths.build),
  '**/*.test.js.snap',
  '**/*.test.jsx',
  '**/*.test.jsx.snap',
  '**/*.ico'
];

if (process.env.NODE_ENV !== 'development') {
  eslintIgnore.push('**/*.test.js');
}

eslintIgnore.push('');

let eslintJSON = {
  'parser': 'babel-eslint',
  'plugins': [
    'react'
  ],
  'rules': {
    'max-len': [
      1,
      120,
      2,
      {
        'ignoreComments': true
      }
    ],
    'semi': [2, 'always'],
    'padded-blocks': 0,
    'new-cap': 0,
    'react/jsx-tag-spacing': 0,
    'react/prop-types': 0
  },
  'extends': [
    'standard',
    'standard-react'
  ]
};

if (process.env.NODE_ENV === 'development') {
  eslintJSON.plugins.push('only-warn');
  eslintJSON.plugins.push('jest');
  eslintJSON.env = {
    'jest/globals': true
  };
}

module.exports = function () {
  FileWriter.write('.eslintignore', eslintIgnore.join('\n'));
  FileWriter.write('.eslintrc', [ JSON.stringify(eslintJSON, null, 2) ].join('\n'));
};
